# Generated by Django 3.1.2 on 2020-10-07 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EventRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=200)),
                ('expected_budget', models.IntegerField(default=0)),
                ('from_date', models.DateTimeField(verbose_name='From')),
                ('to_date', models.DateTimeField(verbose_name='To')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEP.client')),
            ],
        ),
    ]
