# Generated by Django 3.1.2 on 2020-10-08 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SEP', '0002_auto_20201007_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('attendees', models.IntegerField(default=0)),
                ('expected_budget', models.IntegerField(default=0)),
                ('from_date', models.DateTimeField(verbose_name='From')),
                ('to_date', models.DateTimeField(verbose_name='To')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEP.client')),
            ],
        ),
        migrations.DeleteModel(
            name='EventRequest',
        ),
    ]
