# Generated by Django 3.1.2 on 2020-10-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SEP', '0003_auto_20201008_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='organized_events',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='computers',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='decorations',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='film_and_photos',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='food_drinks',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='music',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='other',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='posters_art',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
