# Generated by Django 3.1.2 on 2020-10-08 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SEP', '0004_auto_20201008_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('attendees', models.IntegerField(default=0)),
                ('expected_budget', models.IntegerField(default=0)),
                ('from_date', models.DateTimeField(verbose_name='From')),
                ('to_date', models.DateTimeField(verbose_name='To')),
                ('decorations', models.CharField(max_length=500)),
                ('film_and_photos', models.CharField(max_length=500)),
                ('posters_art', models.CharField(max_length=500)),
                ('food_drinks', models.CharField(max_length=500)),
                ('music', models.CharField(max_length=500)),
                ('computers', models.CharField(max_length=500)),
                ('other', models.CharField(max_length=500)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEP.client')),
            ],
        ),
    ]
