# Generated by Django 3.1.2 on 2020-10-08 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SEP', '0005_requestevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestevent',
            name='client',
            field=models.CharField(max_length=10),
        ),
    ]
