# Generated by Django 3.1.2 on 2020-10-08 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SEP', '0006_auto_20201008_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestevent',
            name='status',
            field=models.CharField(default='created', max_length=10),
            preserve_default=False,
        ),
    ]
