# Generated by Django 3.1.2 on 2020-10-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SEP', '0008_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='requestevent',
            name='client',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='requestevent',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
